# Generated by Django 6.0.1 on 2026-01-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_average', models.FloatField(help_text='Current average quiz score')),
                ('quiz_count', models.IntegerField(default=0, help_text='Number of quizzes taken')),
                ('predicted_grade', models.FloatField(help_text='AI predicted final grade (0-100)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in prediction (0-1)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=20)),
                ('performance_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], max_length=20)),
                ('strong_topics', models.JSONField(default=list, help_text='List of topics student excels in')),
                ('weak_topics', models.JSONField(default=list, help_text='List of topics needing improvement')),
                ('recommendations', models.TextField(blank=True, help_text='AI-generated study recommendations')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_forecasts', to='LMS.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_forecasts', to='LMS.subject')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='QuizTopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Quiz or question topic/category', max_length=255)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performance', to='LMS.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performance', to='LMS.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'topic')},
            },
        ),
    ]
