# Generated by Django 4.2.27 on 2026-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_admin_teacher_remove_grade_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='performance',
        ),
        migrations.AddField(
            model_name='student',
            name='gradeLevel',
            field=models.CharField(choices=[('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
