# Generated by Django 6.0.1 on 2026-01-14 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_gradeforecast_quiztopicperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], max_length=2)),
                ('written_work_score', models.FloatField(default=0.0, help_text='Total WW score')),
                ('written_work_total', models.FloatField(default=100.0, help_text='Total possible WW points')),
                ('performance_task_score', models.FloatField(default=0.0, help_text='Total PT score')),
                ('performance_task_total', models.FloatField(default=100.0, help_text='Total possible PT points')),
                ('quarterly_assessment_score', models.FloatField(default=0.0, help_text='Quarterly exam score')),
                ('quarterly_assessment_total', models.FloatField(default=100.0, help_text='Total possible QA points')),
                ('ww_weight', models.FloatField(default=0.4, help_text='Written Work weight (0-1)')),
                ('pt_weight', models.FloatField(default=0.4, help_text='Performance Task weight (0-1)')),
                ('qa_weight', models.FloatField(default=0.2, help_text='Quarterly Assessment weight (0-1)')),
                ('final_grade', models.FloatField(default=0.0, help_text='Weighted final grade (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, help_text='Teacher comments/remarks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_grades', to='LMS.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_grades', to='LMS.subject')),
            ],
            options={
                'ordering': ['student', 'subject', 'quarter'],
                'unique_together': {('student', 'subject', 'quarter')},
            },
        ),
    ]
