# Generated by Django 4.2.27 on 2026-01-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_remove_student_gpa_remove_student_performance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='gradeLevel',
            new_name='grade_level',
        ),
    ]
