# Generated by Django 6.0.1 on 2026-01-28 10:31

import LMS.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_subjectofferingfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='grade_type',
            field=models.CharField(choices=[('WRITTEN_WORK', 'Written Work'), ('PERFORMANCE_TASK', 'Performance Task'), ('QUARTERLY_EXAM', 'Quarterly Exam')], default='WRITTEN_WORK', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to=LMS.models.quiz_answer_file_path),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='manually_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
    ]
