# Generated by Django 4.2.27 on 2026-01-14 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_rename_gradelevel_student_grade_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade_level', models.CharField(choices=[('GRADE_7', 'Grade 7'), ('GRADE_8', 'Grade 8'), ('GRADE_9', 'Grade 9'), ('GRADE_10', 'Grade 10')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade_level', 'name'],
                'unique_together': {('name', 'grade_level')},
            },
        ),
    ]
