# Generated by Django 6.0 on 2026-08-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_schoolyear_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quarter',
        ),
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='LMS.semester'),
        ),
    ]
