# Generated by Django 6.0 on 2026-08-10 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_remove_quiz_quarter_quiz_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='LMS.semester'),
        ),
    ]
