# Generated by Django 4.2.27 on 2026-01-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_student_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='school_id',
        ),
    ]
