# Generated by Django 6.0 on 2026-08-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0007_alter_quiz_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade_type',
            field=models.CharField(choices=[('WRITTEN_WORK', 'Written Work'), ('PERFORMANCE_TASK', 'Performance Task'), ('FINAL_EXAM', 'Final Exam')], default='WRITTEN_WORK', max_length=20),
        ),
    ]
