# Generated by Django 4.2.27 on 2026-01-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='section',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
