# Generated by Django 4.2.27 on 2026-09-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0008_alter_quiz_grade_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quarterlygrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quarterlygrade',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Required for new semester grades; null only for legacy quarterly records.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='LMS.semester'),
        ),
        migrations.AlterField(
            model_name='quarterlygrade',
            name='quarter',
            field=models.CharField(blank=True, choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], default='', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='quarterlygrade',
            constraint=models.UniqueConstraint(fields=('student', 'SubjectOffering', 'semester'), name='unique_student_offering_semester'),
        ),
        migrations.AddConstraint(
            model_name='quarterlygrade',
            constraint=models.UniqueConstraint(condition=models.Q(('semester__isnull', True)), fields=('student', 'SubjectOffering', 'quarter'), name='unique_legacy_student_offering_quarter'),
        ),
    ]
