# Generated by Django 4.2.27 on 2026-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_alter_quarterlygrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='activity_mode',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GROUP', 'By Group')], default='INDIVIDUAL', max_length=10),
        ),
    ]
