# Generated by Django 4.2.27 on 2026-01-20 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_remove_teacher_advisor_remove_teacher_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='LMS.section'),
            preserve_default=False,
        ),
    ]
