# Generated by Django 4.2.27 on 2026-09-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_quiz_activity_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='group_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='QuizActivityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('members', models.ManyToManyField(blank=True, related_name='quiz_activity_groups', to='LMS.student')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_groups', to='LMS.quiz')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
