# Generated by Django 4.2.27 on 2026-01-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='LMS.section'),
        ),
    ]
