# Generated by Django 4.2.27 on 2026-09-12 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_quiz_group_revision_quizactivitygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizactivitygroup',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizactivitygroup',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_activity_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizactivitygroup',
            name='grading_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizactivitygroup',
            name='question_grades',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizactivitygroup',
            name='source_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_source_for', to='LMS.quizattempt'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grade_credits', to='LMS.quizactivitygroup'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='unique_group_grade_credit'),
        ),
    ]
