# Generated by Django 4.2.27 on 2026-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0011_alter_subject_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='LMS.section'),
        ),
    ]
