# Generated by Django 4.2.27 on 2026-01-21 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_remove_subject_section_subject_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='LMS.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='LMS.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('subject', 'section', 'teacher')},
            },
        ),
    ]
