# Generated by Django 4.2.27 on 2026-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0012_quizactivitygroup_graded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
