# Generated by Django 4.2.27 on 2026-01-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_remove_subject_section_subjectoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='LMS.section'),
        ),
    ]
