# Generated by Django 4.2.27 on 2026-01-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_subject_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject', 'section')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AddField(
            model_name='subject',
            name='sections',
            field=models.ManyToManyField(related_name='subjects', through='LMS.SubjectOffering', to='LMS.section'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TEACHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
