# Generated by Django 4.2.27 on 2026-01-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_alter_subjectoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sections',
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='subject_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('subject_name', 'section')},
        ),
        migrations.RemoveField(
            model_name='subjectoffering',
            name='subject',
        ),
    ]
