# Generated by Django 4.2.27 on 2026-01-21 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0016_alter_subjectoffering_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectoffering',
            old_name='subject_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='subjectoffering',
            unique_together={('name', 'section')},
        ),
    ]
