# Generated by Django 4.2.27 on 2026-01-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0017_rename_subject_name_subjectoffering_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('time_limit', models.IntegerField(help_text='Minutes to complete quiz')),
                ('total_points', models.FloatField(default=100)),
                ('passing_score', models.FloatField(default=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('OPEN', 'Open'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('allow_multiple_attempts', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='LMS.subjectoffering')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='LMS.subjectoffering')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MULTIPLE_CHOICE', 'Multiple Choice'), ('TRUE_FALSE', 'True/False'), ('SHORT_ANSWER', 'Short Answer')], default='MULTIPLE_CHOICE', max_length=20)),
                ('points', models.FloatField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='LMS.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='LMS.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='IN_PROGRESS', max_length=20)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='LMS.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='LMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.FloatField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='LMS.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LMS.quizquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMS.quizchoice')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=50, unique=True)),
                ('assignment_name', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='LMS.subjectoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='LMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTopicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(help_text='Quiz or question topic/category', max_length=255)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performance', to='LMS.subjectoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_performance', to='LMS.student')),
            ],
            options={
                'unique_together': {('student', 'SubjectOffering', 'topic')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], max_length=2)),
                ('written_work_score', models.FloatField(default=0.0, help_text='Total WW score')),
                ('written_work_total', models.FloatField(default=100.0, help_text='Total possible WW points')),
                ('performance_task_score', models.FloatField(default=0.0, help_text='Total PT score')),
                ('performance_task_total', models.FloatField(default=100.0, help_text='Total possible PT points')),
                ('quarterly_assessment_score', models.FloatField(default=0.0, help_text='Quarterly exam score')),
                ('quarterly_assessment_total', models.FloatField(default=100.0, help_text='Total possible QA points')),
                ('ww_weight', models.FloatField(default=0.4, help_text='Written Work weight (0-1)')),
                ('pt_weight', models.FloatField(default=0.4, help_text='Performance Task weight (0-1)')),
                ('qa_weight', models.FloatField(default=0.2, help_text='Quarterly Assessment weight (0-1)')),
                ('final_grade', models.FloatField(default=0.0, help_text='Weighted final grade (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True, help_text='Teacher comments/remarks')),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_grades', to='LMS.subjectoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_grades', to='LMS.student')),
            ],
            options={
                'ordering': ['student', 'SubjectOffering', 'quarter'],
                'unique_together': {('student', 'SubjectOffering', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='GradeForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_average', models.FloatField(help_text='Current average quiz score')),
                ('quiz_count', models.IntegerField(default=0, help_text='Number of quizzes taken')),
                ('predicted_grade', models.FloatField(help_text='AI predicted final grade (0-100)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in prediction (0-1)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=20)),
                ('performance_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('STABLE', 'Stable'), ('DECLINING', 'Declining')], max_length=20)),
                ('strong_topics', models.JSONField(default=list, help_text='List of topics student excels in')),
                ('weak_topics', models.JSONField(default=list, help_text='List of topics needing improvement')),
                ('recommendations', models.TextField(blank=True, help_text='AI-generated study recommendations')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SubjectOffering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_forecasts', to='LMS.subjectoffering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_forecasts', to='LMS.student')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('student', 'SubjectOffering')},
            },
        ),
    ]
