# Generated by Django 4.2.27 on 2026-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_quiz_resource_quizquestion_quizchoice_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quarter',
            field=models.CharField(choices=[('Q1', 'First Quarter'), ('Q2', 'Second Quarter'), ('Q3', 'Third Quarter'), ('Q4', 'Fourth Quarter')], default='Q1', max_length=2),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_points',
            field=models.FloatField(default=0),
        ),
    ]
