# Generated by Django 4.2.27 on 2026-01-23 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0019_quiz_quarter_alter_quiz_total_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(max_length=255)),
                ('previous_grade', models.CharField(default='N/A', max_length=50)),
                ('new_grade', models.CharField(max_length=50)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update')], max_length=6)),
                ('SubjectOffering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LMS.subjectoffering')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_change_logs_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
