# Generated by Django 4.2.27 on 2026-01-23 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0020_gradechangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradechangelog',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_change_logs_as_student', to='LMS.student'),
        ),
    ]
